version: "3"
services: 
  mysql_knex:
    env_file:
      - .env
    container_name: mysql
    hostname: mysql
    image: mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes: 
      - C:\Users\Prloe\OneDrive\Área de Trabalho\Mysql_docker:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo